import { useState } from "react";
import { readJsonResponse } from "../utils/api";

const questionTypes = [
  { id: "mcq", label: "MCQ" },
  { id: "msq", label: "MSQ" },
  { id: "theory", label: "Theory" },
  { id: "programming", label: "Programming" },
  { id: "true-false", label: "True / False" },
  { id: "file-drop", label: "File Drop" },
];

const blankQuestion = {
  type: "mcq",
  question: "",
  options: ["", "", "", ""],
  answer: "",
  marks: 1,
};

function normalizeQuestion(question) {
  return {
    ...blankQuestion,
    ...question,
    options: Array.isArray(question.options) ? question.options : ["", "", "", ""],
  };
}

export function QuizBuilder({ onToast }) {
  const [title, setTitle] = useState("AI Foundations Quiz");
  const [topic, setTopic] = useState("Model evaluation");
  const [questions, setQuestions] = useState([blankQuestion]);
  const [loading, setLoading] = useState(false);
  const [fileName, setFileName] = useState("");

  function updateQuestion(index, field, value) {
    setQuestions((current) =>
      current.map((question, questionIndex) =>
        questionIndex === index ? { ...question, [field]: value } : question
      )
    );
  }

  function updateOption(questionIndex, optionIndex, value) {
    setQuestions((current) =>
      current.map((question, index) => {
        if (index !== questionIndex) return question;
        const options = [...(question.options || [])];
        options[optionIndex] = value;
        return { ...question, options };
      })
    );
  }

  function addQuestion() {
    setQuestions((current) => [...current, { ...blankQuestion, options: [...blankQuestion.options] }]);
  }

  function handleDrop(event) {
    event.preventDefault();
    const file = event.dataTransfer.files[0];
    setFileName(file?.name || "");
  }

  function handleChooseFile(event) {
    const file = event.target.files[0];
    setFileName(file?.name || "");
  }

  async function generateQuiz() {
    setLoading(true);
    try {
      const response = await fetch("/api/agent/create-quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic,
          count: 6,
          types: questionTypes.map((type) => type.id),
        }),
      });
      const data = await readJsonResponse(response);
      if (!data.ok) throw new Error(data.message);
      setQuestions(data.quiz.map(normalizeQuestion));
      onToast(data.fallback ? "Quiz generated locally because Gemini access is blocked" : "Quiz generated by Gemini");
    } catch (error) {
      onToast(error.message);
    } finally {
      setLoading(false);
    }
  }

  function saveQuiz() {
    onToast(`${title} saved in prototype`);
  }

  return (
    <section className="panel wide" id="create-quiz">
      <div className="panel-heading">
        <div>
          <p className="eyebrow">Create Quiz</p>
          <h2>Quiz Builder</h2>
        </div>
        <button className="secondary-btn" disabled={loading} onClick={generateQuiz}>
          {loading ? "Generating..." : "Create with Agent"}
        </button>
      </div>

      <div className="quiz-meta">
        <label>
          Quiz title
          <input value={title} onChange={(event) => setTitle(event.target.value)} />
        </label>
        <label>
          Topic for agent
          <input value={topic} onChange={(event) => setTopic(event.target.value)} />
        </label>
      </div>

      <div className="drop-zone" onDragOver={(event) => event.preventDefault()} onDrop={handleDrop}>
        <div>
          <strong>Reference file</strong>
          <span title={fileName || "No file attached"}>{fileName || "No file attached"}</span>
        </div>
        <label className="file-picker">
          Choose file
          <input onChange={handleChooseFile} type="file" />
        </label>
      </div>

      <div className="quiz-builder-list">
        {questions.map((question, index) => (
          <article className="quiz-question-card" key={index}>
            <div className="panel-heading">
              <strong>Question {index + 1}</strong>
              <select value={question.type} onChange={(event) => updateQuestion(index, "type", event.target.value)}>
                {questionTypes.map((type) => <option value={type.id} key={type.id}>{type.label}</option>)}
              </select>
            </div>
            <textarea
              value={question.question}
              onChange={(event) => updateQuestion(index, "question", event.target.value)}
              placeholder="Enter question"
            />
            {["mcq", "msq", "true-false"].includes(question.type) && (
              <div className="option-grid">
                {(question.options || []).map((option, optionIndex) => (
                  <input
                    value={option}
                    onChange={(event) => updateOption(index, optionIndex, event.target.value)}
                    placeholder={`Option ${optionIndex + 1}`}
                    key={optionIndex}
                  />
                ))}
              </div>
            )}
            {question.type === "file-drop" && (
              <div className="drop-zone small">
                <div>
                  <strong>Student file answer</strong>
                  <span>Contained upload area for PDFs, images, or code files.</span>
                </div>
              </div>
            )}
            {question.type === "programming" && <textarea placeholder="Starter code or expected output" />}
            <div className="quiz-meta">
              <label>
                Answer
                <input
                  value={Array.isArray(question.answer) ? question.answer.join(", ") : question.answer || ""}
                  onChange={(event) => updateQuestion(index, "answer", event.target.value)}
                />
              </label>
              <label>
                Marks
                <input min="1" type="number" value={question.marks || 1} onChange={(event) => updateQuestion(index, "marks", Number(event.target.value))} />
              </label>
            </div>
          </article>
        ))}
      </div>

      <div className="question-actions">
        <button className="secondary-btn" onClick={addQuestion}>Add Question</button>
        <button className="primary-btn" onClick={saveQuiz}>Save Quiz</button>
      </div>
    </section>
  );
}
